# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Mon Aug  8 12:03:53 2011
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.graphicsView = QtGui.QGraphicsView(self.centralwidget)
        self.graphicsView.setObjectName("graphicsView")
        self.verticalLayout_2.addWidget(self.graphicsView)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.fileChooseLabel = QtGui.QLabel(self.centralwidget)
        self.fileChooseLabel.setObjectName("fileChooseLabel")
        self.verticalLayout_3.addWidget(self.fileChooseLabel)
        self.fileWidget = QtGui.QListWidget(self.centralwidget)
        self.fileWidget.setObjectName("fileWidget")
        self.verticalLayout_3.addWidget(self.fileWidget)
        self.addFileButton = QtGui.QPushButton(self.centralwidget)
        self.addFileButton.setObjectName("addFileButton")
        self.verticalLayout_3.addWidget(self.addFileButton)
        self.doTransformationButton = QtGui.QPushButton(self.centralwidget)
        self.doTransformationButton.setObjectName("doTransformationButton")
        self.verticalLayout_3.addWidget(self.doTransformationButton)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cursorRadiusSlider = QtGui.QSlider(self.centralwidget)
        self.cursorRadiusSlider.setMaximum(999)
        self.cursorRadiusSlider.setProperty("value", 100)
        self.cursorRadiusSlider.setOrientation(QtCore.Qt.Horizontal)
        self.cursorRadiusSlider.setObjectName("cursorRadiusSlider")
        self.horizontalLayout.addWidget(self.cursorRadiusSlider)
        self.cursorRadiusSpinBox = QtGui.QDoubleSpinBox(self.centralwidget)
        self.cursorRadiusSpinBox.setDecimals(1)
        self.cursorRadiusSpinBox.setMaximum(1000.0)
        self.cursorRadiusSpinBox.setProperty("value", 10.0)
        self.cursorRadiusSpinBox.setObjectName("cursorRadiusSpinBox")
        self.horizontalLayout.addWidget(self.cursorRadiusSpinBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.statsNumber = QtGui.QLabel(self.centralwidget)
        self.statsNumber.setObjectName("statsNumber")
        self.verticalLayout_3.addWidget(self.statsNumber)
        self.statsIntensity = QtGui.QLabel(self.centralwidget)
        self.statsIntensity.setText("")
        self.statsIntensity.setObjectName("statsIntensity")
        self.verticalLayout_3.addWidget(self.statsIntensity)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.zoomOutButton = QtGui.QPushButton(self.centralwidget)
        self.zoomOutButton.setObjectName("zoomOutButton")
        self.verticalLayout_3.addWidget(self.zoomOutButton)
        self.zoomInButton = QtGui.QPushButton(self.centralwidget)
        self.zoomInButton.setObjectName("zoomInButton")
        self.verticalLayout_3.addWidget(self.zoomInButton)
        self.gridLayout.addLayout(self.verticalLayout_3, 0, 1, 1, 1)
        self.gridLayout.setColumnStretch(0, 20)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 25))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuExtras = QtGui.QMenu(self.menubar)
        self.menuExtras.setObjectName("menuExtras")
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionTransformation_Matrix = QtGui.QAction(MainWindow)
        self.actionTransformation_Matrix.setObjectName("actionTransformation_Matrix")
        self.actionExport_Composed_image = QtGui.QAction(MainWindow)
        self.actionExport_Composed_image.setObjectName("actionExport_Composed_image")
        self.actionExport_as_stack_of_images = QtGui.QAction(MainWindow)
        self.actionExport_as_stack_of_images.setObjectName("actionExport_as_stack_of_images")
        self.actionAuto_detect_beads = QtGui.QAction(MainWindow)
        self.actionAuto_detect_beads.setObjectName("actionAuto_detect_beads")
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionClear_all = QtGui.QAction(MainWindow)
        self.actionClear_all.setObjectName("actionClear_all")
        self.actionExport_transformed_coordinates = QtGui.QAction(MainWindow)
        self.actionExport_transformed_coordinates.setObjectName("actionExport_transformed_coordinates")
        self.menuFile.addAction(self.actionExport_Composed_image)
        self.menuFile.addAction(self.actionExport_as_stack_of_images)
        self.menuFile.addAction(self.actionExport_transformed_coordinates)
        self.menuView.addAction(self.actionTransformation_Matrix)
        self.menuExtras.addAction(self.actionAuto_detect_beads)
        self.menuExtras.addAction(self.actionClear_all)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuExtras.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "ColorComposer", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Preview", None, QtGui.QApplication.UnicodeUTF8))
        self.fileChooseLabel.setText(QtGui.QApplication.translate("MainWindow", "File List", None, QtGui.QApplication.UnicodeUTF8))
        self.addFileButton.setText(QtGui.QApplication.translate("MainWindow", "Add File...", None, QtGui.QApplication.UnicodeUTF8))
        self.doTransformationButton.setText(QtGui.QApplication.translate("MainWindow", "Transformation", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Cursor Radius:", None, QtGui.QApplication.UnicodeUTF8))
        self.statsNumber.setText(QtGui.QApplication.translate("MainWindow", "Statistics: no beads", None, QtGui.QApplication.UnicodeUTF8))
        self.zoomOutButton.setText(QtGui.QApplication.translate("MainWindow", "zoom -", None, QtGui.QApplication.UnicodeUTF8))
        self.zoomInButton.setText(QtGui.QApplication.translate("MainWindow", "zoom +", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuView.setTitle(QtGui.QApplication.translate("MainWindow", "View", None, QtGui.QApplication.UnicodeUTF8))
        self.menuExtras.setTitle(QtGui.QApplication.translate("MainWindow", "Extras", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTransformation_Matrix.setText(QtGui.QApplication.translate("MainWindow", "Transformation Matrix...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExport_Composed_image.setText(QtGui.QApplication.translate("MainWindow", "Export Composed image...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExport_as_stack_of_images.setText(QtGui.QApplication.translate("MainWindow", "Export as stack of images...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAuto_detect_beads.setText(QtGui.QApplication.translate("MainWindow", "Auto-detect beads", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClear_all.setText(QtGui.QApplication.translate("MainWindow", "Discard loaded images (Reset)", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExport_transformed_coordinates.setText(QtGui.QApplication.translate("MainWindow", "Export transformed Coordinates as List...", None, QtGui.QApplication.UnicodeUTF8))

