# Search for rudeconfig headers
INCLUDE(FindPackageMessage)

FIND_PATH(RUDECONFIG_INCLUDE_DIR rude/config.h)
FIND_LIBRARY(RUDECONFIG_LIBRARIES NAMES rudeconfig)

SET(RUDECONFIG_FOUND FALSE)
IF(RUDECONFIG_INCLUDE_DIR AND RUDECONFIG_INCLUDE_DIR)
    FIND_PACKAGE_MESSAGE(RUDECONFIG "Found RudeConfig: ${RUDECONFIG_LIBRARIES}" "[${RUDECONFIG_LIBRARIES}][${RUDECONFIG_INCLUDE_DIR}]")
    SET(RUDECONFIG_FOUND TRUE)
ENDIF()

MARK_AS_ADVANCED(
    RUDECONFIG_INCLUDE_DIR
    RUDECONFIG_LIBRARIES
    RUDECONFIG_FOUND
)

